import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { useExpenseStore, Group } from '@/stores/expenseStore';
import { BarChart3, PieChart, TrendingUp, DollarSign, Download } from 'lucide-react';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart as RechartsPieChart,
  Cell,
  Pie,
} from 'recharts';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import  exportGroupAnalyticsToPDF from './ExportGroupAnalyticsToPDF';

interface GroupAnalyticsProps {
  group: Group;
}

const COLORS = [
  '#3b82f6',
  '#ef4444',
  '#10b981',
  '#f59e0b',
  '#8b5cf6',
  '#ec4899',
  '#06b6d4',
  '#84cc16',
];

// Helper: Format currency
const formatCurrency = (amount: number) => `${amount.toFixed(2)}`;

// Helper: Add PDF footer to all pages
function addPDFFooter(doc: jsPDF, groupName: string) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Generated by Expense Tracker - Page ${i} of ${pageCount}`,
      105,
      285,
      { align: 'center' }
    );
  }
}

// Helper: Safe filename
function getSafeFileName(name: string) {
  return name.replace(/[^a-z0-9]/gi, '_').toLowerCase();
}

export const GroupAnalytics: React.FC<GroupAnalyticsProps> = ({ group }) => {
  const { getGroupAnalytics, getGroupExpenses } = useExpenseStore();
  const analytics = getGroupAnalytics(group.id);
  const expenses = getGroupExpenses(group.id);

  // Prepare member spending data
  const memberSpendingData = React.useMemo(
    () =>
      Object.entries(analytics.memberSpending)
        .map(([memberId, amount]) => {
          const member = group.members.find((m) => m.userId == memberId);
          const numAmount = Number(amount);
          return {
            name: member?.name || 'Unknown',
            amount: numAmount,
            percentage: (numAmount / analytics.totalSpent) * 100,
          };
        })
        .sort((a, b) => b.amount - a.amount),
    [analytics.memberSpending, analytics.totalSpent, group.members]
  );

  // Prepare category spending data
  const categorySpendingData = React.useMemo(
    () =>
      Object.entries(analytics.categorySpending)
        .map(([category, amount]) => {
          const numAmount = Number(amount);
          return {
            name: category.charAt(0).toUpperCase() + category.slice(1),
            amount: numAmount,
            percentage: (numAmount / analytics.totalSpent) * 100,
          };
        })
        .sort((a, b) => b.amount - a.amount),
    [analytics.categorySpending, analytics.totalSpent]
  );

  // Monthly spending trend (last 6 months)
  const monthlyData = React.useMemo(() => {
    const months = [];
    const now = new Date();
    for (let i = 5; i >= 0; i--) {
      const month = new Date(now.getFullYear(), now.getMonth() - i, 1);
      const monthExpenses = expenses.filter((expense) => {
        const expenseDate = new Date(expense.date);
        return (
          expenseDate.getMonth() === month.getMonth() &&
          expenseDate.getFullYear() === month.getFullYear()
        );
      });
      months.push({
        month: month.toLocaleString('default', { month: 'short' }),
        amount: monthExpenses.reduce((sum, expense) => sum + expense.amount, 0),
        count: monthExpenses.length,
      });
    }
    return months;
  }, [expenses]);

  // PDF Export


  if (analytics.totalSpent === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center space-x-2">
            <BarChart3 className="w-5 h-5" />
            <span>Group Analytics</span>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-center py-8">
            <BarChart3 className="w-12 h-12 mx-auto text-gray-400 mb-4" />
            <p className="text-gray-600">No expenses to analyze</p>
            <p className="text-sm text-gray-500">
              Add some expenses to see analytics
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {/* Export Button */}
      <div className="flex justify-end">
       <Button
  onClick={() =>
    exportGroupAnalyticsToPDF({
      group,
      analytics,
      expenses,
      memberSpendingData,
      categorySpendingData,
      monthlyData,
    })
  }
  variant="outline"
  className="flex items-center gap-2"
>
          <Download className="w-4 h-4" />
          Export Analytics PDF
        </Button>
      </div>
      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center space-x-2">
              <DollarSign className="w-5 h-5 text-green-500" />
              <div>
                <div className="text-2xl font-bold text-green-600">
                 {group.settings.currency}{formatCurrency(analytics.totalSpent)}
                </div>
                <p className="text-sm text-gray-600">Total Spent</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-4">
            <div className="flex items-center space-x-2">
              <BarChart3 className="w-5 h-5 text-blue-500" />
              <div>
                <div className="text-2xl font-bold text-blue-600">
                  {group.settings.currency}{formatCurrency(
                    analytics.totalSpent / group.members.length
                  )}
                </div>
                <p className="text-sm text-gray-600">Avg per Person</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-4">
            <div className="flex items-center space-x-2">
              <TrendingUp className="w-5 h-5 text-purple-500" />
              <div>
                <div className="text-2xl font-bold text-purple-600">
                  {analytics.expenseCount}
                </div>
                <p className="text-sm text-gray-600">Total Expenses</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-4">
            <div className="flex items-center space-x-2">
              <PieChart className="w-5 h-5 text-orange-500" />
              <div>
                <div className="text-2xl font-bold text-orange-600">
                  {Object.keys(analytics.categorySpending).length}
                </div>
                <p className="text-sm text-gray-600">Categories</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Member Spending */}
        <Card>
          <CardHeader>
            <CardTitle>Spending by Member</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {memberSpendingData.map((member) => (
                <div key={member.name} className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="font-medium">{member.name}</span>
                    <span className="text-gray-600">
                      {group.settings.currency}{formatCurrency(member.amount)} ({member.percentage.toFixed(1)}%)
                    </span>
                  </div>
                  <Progress value={member.percentage} className="h-2" />
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Category Breakdown */}
        <Card>
          <CardHeader>
            <CardTitle>Spending by Category</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {categorySpendingData.map((category) => (
                <div key={category.name} className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="font-medium">{category.name}</span>
                    <span className="text-gray-600">
                      {group.settings.currency}{formatCurrency(category.amount)} ({category.percentage.toFixed(1)}%)
                    </span>
                  </div>
                  <Progress value={category.percentage} className="h-2" />
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Monthly Trend */}
      <Card>
        <CardHeader>
          <CardTitle>Spending Trend (Last 6 Months)</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={monthlyData}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="month" />
                <YAxis />
                <Tooltip
                  formatter={(value: number) => [formatCurrency(value), `Amount(${group.settings.currency})`]}
                  labelFormatter={(label) => `${label}`}
                />
                <Bar dataKey="amount" fill="#3b82f6" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </CardContent>
      </Card>

      {/* Category Pie Chart */}
      <Card>
        <CardHeader>
          <CardTitle>Category Distribution</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <RechartsPieChart>
                <Pie
                  data={categorySpendingData}
                  cx="50%"
                  cy="50%"
                  outerRadius={80}
                  dataKey="amount"
                  label={({ name, percentage }) =>
                    `${name} (${percentage.toFixed(1)}%)`
                  }
                >
                  {categorySpendingData.map((entry, index) => (
                    <Cell
                      key={`cell-${index}`}
                      fill={COLORS[index % COLORS.length]}
                    />
                  ))}
                </Pie>
                <Tooltip
                  formatter={(value: number) => [formatCurrency(value), 'Amount']}
                />
              </RechartsPieChart>
            </ResponsiveContainer>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};